apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: manbharpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: manbharpipelinesjavascriptdocker 
    spec:
      containers:
        - name: manbharpipelinesjavascriptdocker 
          image: manbharcontainerregistry.azurecr.io/manbharpipelinesjavascriptdocker
          ports:
          - containerPort: 8080